INSERT INTO Nation(name) VALUES('Alaska');
INSERT INTO Nation(name) VALUES('Alberta');
INSERT INTO Nation(name) VALUES('America Centrale');
INSERT INTO Nation(name) VALUES('Stati Uniti Orientali');
INSERT INTO Nation(name) VALUES('Groenlandia');
INSERT INTO Nation(name) VALUES('Territori del Nord Ovest');
INSERT INTO Nation(name) VALUES('Ontario');
INSERT INTO Nation(name) VALUES('Quebec');
INSERT INTO Nation(name) VALUES('Stati Uniti Occidentali');
INSERT INTO Nation(name) VALUES('Argentina');
INSERT INTO Nation(name) VALUES('Brasile');
INSERT INTO Nation(name) VALUES('Peru`');
INSERT INTO Nation(name) VALUES('Venezuela');
INSERT INTO Nation(name) VALUES('Gran Bretagna');
INSERT INTO Nation(name) VALUES('Islanda');
INSERT INTO Nation(name) VALUES('Europa Settentrionale');
INSERT INTO Nation(name) VALUES('Scandinavia');
INSERT INTO Nation(name) VALUES('Europa Meridionale');
INSERT INTO Nation(name) VALUES('Ucraina');
INSERT INTO Nation(name) VALUES('Europa Occidentale');
INSERT INTO Nation(name) VALUES('Congo');
INSERT INTO Nation(name) VALUES('Africa Orientale');
INSERT INTO Nation(name) VALUES('Egitto');
INSERT INTO Nation(name) VALUES('Madagascar');
INSERT INTO Nation(name) VALUES('Africa del Nord');
INSERT INTO Nation(name) VALUES('Africa Meridionale');
INSERT INTO Nation(name) VALUES('Afghanistan');
INSERT INTO Nation(name) VALUES('Cina');
INSERT INTO Nation(name) VALUES('India');
INSERT INTO Nation(name) VALUES('Cita');
INSERT INTO Nation(name) VALUES('Giappone');
INSERT INTO Nation(name) VALUES('Kamchatka');
INSERT INTO Nation(name) VALUES('Medio Oriente');
INSERT INTO Nation(name) VALUES('Mongolia');
INSERT INTO Nation(name) VALUES('Siam');
INSERT INTO Nation(name) VALUES('Siberia');
INSERT INTO Nation(name) VALUES('Urali');
INSERT INTO Nation(name) VALUES('Jacuzia');
INSERT INTO Nation(name) VALUES('Australia Orientale');
INSERT INTO Nation(name) VALUES('Indonesia');
INSERT INTO Nation(name) VALUES('Nuova Guinea');
INSERT INTO Nation(name) VALUES('Australia Occidentale');